### PR TITLE
Add Emscripten support.

### PR DESCRIPTION
**Pull request by crlf-code**
This adds necessary changes for building and using DiligentCore with emscripten toolchain. 

The cmake config files are untested. But the code has been used to write an internal demo, and it works to a degree.

### CODE REVIEW

**Comment by TheMostDiligent** [comment]
@crlf-code Thanks for submitting this! We will take a look and merge this PR, only a bit later (need to finish few other things first).

**Comment by logankaser** [comment]
What is the status of this, has it been abandoned? I could try to resolve the conflicts if that would be helpful. Are you done with the things you needed to do @TheMostDiligent ?

**Comment by TheMostDiligent** [comment]
@logankaser No, this has not been abandoned. We just did not have time to merge this in and as a matter of fact were planning to work on this very soon, so if you can update the PR and fix the conflicts, this will be very helpful.

**Comment by logankaser** [comment]
> @logankaser No, this has not been abandoned. We just did not have time to merge this in and as a matter of fact were planning to work on this very soon, so if you can update the PR and fix the conflicts, this will be very helpful.

I should be able to do this sometime this weekend.

**Comment by logankaser** [comment]
Rebased and opened new PR here: #267

**Comment by TheMostDiligent** [comment]
Merged in https://github.com/DiligentGraphics/DiligentCore/commit/29c5c5cc1813274d96ee9a2f19a7dc08c747450f

**Pull request closed without merging**
