### PR TITLE
Whitespace and spelling fix

### PR DESCRIPTION
**Pull request by logankaser**
Fixes whitespace in all files and fixes many spelling and grammatical errors.
Renames `DXCompilerBaseLiunx.hpp` to `DXCompilerBaseLinux.hpp`
Improves `.gitignore` with some common ignores, including for VSCode and MacOs, Linux and Windows temporary files.

I kept this all together because I was worried about conflicts.

### CODE REVIEW

**Comment by TheMostDiligent** [comment]
Could you have the changes separated: whitespace fix in one PR and other changes - in another?

**Comment by logankaser** [comment]
> Could you have the changes separated: whitespace fix in one PR and other changes - in another?

I think I can separate out the `.gitignore` and the header file rename, but the whitespace and spelling fixes are pretty entangled, some on the same line. Let me know if that works and I'll do that.

**Comment by logankaser** [comment]
> Could you have the changes separated: whitespace fix in one PR and other changes - in another?

Also, technically, this changes the license text one place because someone replaced `gligen` globally with another termed, and it messed up the file header's usage of `negligence`. I reverted that file to be the same as all the others.

**Comment by TheMostDiligent** [comment]
There are 1186 files changed in this PR that contain unrelated changes (white spaces, renames, grammar, etc.).
Most of these files are affected because of white spaces. I would prefer to have a PR that only fixes whitespaces. 
Other changes are not going to affect that many files, so it will be much easier to review them separately.

**Pull request closed without merging**
