### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S ./ThirdParty,*.gltf -L boundimg,delimeter,delimeters,inout,lod,pres,ser,wser`

### CODE REVIEW

**Comment by TheMostDiligent** [comment]
This PR changes the SPIRV-Tools submodule, which is apparently an oversight

**Comment by luzpaz** [comment]
Sorry, thought i excluded those. Reverted and squashed

**Comment by TheMostDiligent** [comment]
@luzpaz Would you consider adding the tool to our [pre-checks action](https://github.com/DiligentGraphics/DiligentCore/blob/master/.github/workflows/pre_checks.yml) to catch the typos before the slip through:

**Comment by TheMostDiligent** [comment]
Merged in https://github.com/DiligentGraphics/DiligentCore/commit/4ee66b631168df5a379f044fe17fe87e8a05cc67

**Pull request closed without merging**
