### PR TITLE
use ENABLE_RTTI flag the same way as glslang

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
glslang has ENABLE_RTTI flag. I have done the same in Diligent to harmonize work around this flag

### CODE REVIEW

**Comment by TheMostDiligent** [comment]
Diligent requires RTTI in debug build as it performs run-time type checks. Without RTTI nothing will run in Debug. In release build RTTI is always disabled.

**Comment by AndreyMlashkin** [comment]
Current implementation does not leave a possibility of a lib user to choose, if he needs RTTI in release mode, as, for example glslang.
I have just copied parts of code from glslang to CMake root.

**Comment by TheMostDiligent** [comment]
> Current implementation does not leave a possibility of a lib user to choose, if he needs RTTI in release mode, as, for example glslang.

Like I said, the library uses RTTI in debug mode to perform run-time type checks. Without RTTI all these checks will fail. In release mode these checks are not performed and RTTI is always disabled - there is no reason to enable it.
The user don't have an option to disable features that are required for the library to work properly.

> I have just copied parts of code from glslang to CMake root.

What works for one project does not necessarily work verbatim or is needed at all for another.

**Comment by AndreyMlashkin** [comment]
Could you then explain me, why do you need to disable rtti only for MSVC?

**Comment by TheMostDiligent** [comment]
RTTI should be disabled for other compilers in release configurations too. It is an oversight it is not disabled.

**Comment by AndreyMlashkin** [comment]
of course it breaks debug builds as default value set to OFF in PR

**Comment by TheMostDiligent** [comment]
So what is the value of the PR that expectedly breaks the build? Do you realize that this change will break the build of *all* customers who use the engine?

**Pull request closed without merging**
