### PR TITLE
Vulkan android

### PR DESCRIPTION
**Pull request by dom607**
First version of vulkan android.

Because of vulkan characteristic (one-API) and your past work thankfully, there are not much to add.

DiligentCore commit:https://github.com/DiligentGraphics/DiligentCore/commit/5fbed684686170ee282e7f2967dcf00dea895fe5 is merged. When merge latest commit:https://github.com/DiligentGraphics/DiligentCore/commit/b86ce3034093752225d73cba23c67ef063a02133 , following runtime error occurred.

```
E/Diligent Engine: Diligent Engine: ERROR: Failed to parse shader source: 
ERROR: #version: versions before 150 do not allow a profile token
ERROR: #version: compute shaders require es profile with version 310 or above, or non-es profile with version 420 or above
WARNING: 0:2: '#extension' : extension not supported: GL_EXT_separate_shader_objects
ERROR: 1 compilation errors.  No code generated.
A/Diligent Engine: Diligent Engine: CRITICAL ERROR in ShaderVkImpl() (ShaderVkImpl.cpp, 68): Failed to compile shader
E/Diligent Engine: Diligent Engine: ERROR in CreateDeviceObject() (RenderDeviceBase.h, 462): Failed to create shader object "Generate mips rgba8 even"
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 32463 (Thread-2), pid 32433 (gentandroidtest)
```

I tested vulkan version diligentSamples last week. It works fine except tessellation, geometry, atmosphere samples, as I mailed. 

### Dev & test Environment
OS : MacOS 10.14.3
Android Studio : 3.3.1
NDK : 19.1
CMAKE : 3.10.2
Test device is Xiaomi POCO F1. 
Tested arch : arm64-v8a ( vulkan, opengl ), armeabi-v7a ( opengl )
Tested platform : 24, 26, 27, 28 ( DiligentSamples have been tested with android-24 only )

### Requirements
CMake : 3.10
minSDKVersion : 24
ABI : arm64-v8a

### TODO
- x86_64 device test
- Cross platform build test.
- and so on.

Feedback and comment are welcome!

### CODE REVIEW

**Comment by DiligentGraphics** [comment]
Is it required to have different vulkan.so libraries for different Android versions? Will it not be OK to have just one libary for each architecture?

**Comment by dom607** [comment]
In my case, android-24 version vulkan lib work fine. If there are ndk package, find_library function will be find vulkan library in NDK_DIR first, not a external path. And this vulkan lib version will be same as minSDKVersion. Just, I'm not sure about other platform's dev environment. So, I place them there for insurance purpose.

**Comment by dom607** [comment]
I have question about SPIRVUtils.cpp. Are shaderc.hpp and native_app_glue.h in use? It doesn't seem to be in use. Even without them, there is no error.

**Comment by DiligentGraphics** [comment]
I guess since you absolutely have to have NDK installed on the system to build for Android, and vulkan.so is already present in the NDK, there is no need to have the copies of libraries in the repo. For other platforms this is not the case: you may not have VulkanSDK on Windows, but you will still be able to successfully build the engine.

What to shaderc.hpp and native_app_glue.h, I just copy-pasted this code from some other project and never tested it. If these files are not needed - great.

For some reason, these (Vulkan samples) use shaderc on Vulkan instead of glslang. Do you know why they do this if glslang works fine as it turns out?

**Comment by dom607** [comment]
I see. I'll unify lib to one per ABI.
I don't know much about shaderc. In my understand, main benefit of shaderc is easy to use. It is easy to attach. And it provide built-in utility functions such as ``` options.AddMacroDefinition("MY_DEFINE", "1"); ``` . But it has big binary file size and compile time. And shaderc is official compiler of glsl on android.

**Comment by DiligentGraphics** [comment]
As far as I learned out, shaderc is a wrapper around glslang and SPIRV-Tools, so there is no need to use it. 
Do we need to have vulkan binaries at all in the repo? Didn't you say that the library is already present in the NDK?
Could you please also share you changes to samples/tutorials?

**Comment by dom607** [comment]
I think, I didn't get it well your last comment. (Sorry about my poor english skill) As I understand, in other platform, android NDK may not be there. That's why I left it on the project. If that's what I got wrong, we don't need extra binaries. And I found ```${ANDROID_NDK}``` in use in DiligentCore directory. It seems already DiligentCore has android NDK dependency.

I'll let you know about sample/tutorial change after merge latest commit and test. It may takes time.

**Comment by DiligentGraphics** [comment]
Don't worry about your English, it is totally fine!
Diligent has vulkan binaries for Windows and Linux to avoid extra dependencies. So you do not need to install Vulkan SDK to build the engine for Windows or Linux.
However to build the engine for Android, you need NDK anyway because otherwise you will not be able to compile c++ code. My point was that since NDK already contains vulkan.so, there is no need to have a copy in the repo (git does not play well with binary files in general).

**Comment by dom607** [comment]
I understood. Then, I think it's OK to get rid of vulkan binaries from engine.

**Comment by dom607** [comment]
After replace this code on GLSLSourceBuilder.cpp, shaderVKImpl generate error. 
(commit : https://github.com/DiligentGraphics/DiligentCore/commit/a93c8f764724651c9fdfe059e20c7c714b355e9d#diff-f8754f24a7893dcb3ed3c45f7d046865L102)
from 
``` 
#elif PLATFORM_ANDROID
    GLSLSource.append(
        "#version 310 es\n"
        "#extension GL_EXT_texture_cube_map_array : enable\n"
    );
``` 
to 
```
#elif PLATFORM_ANDROID || PLATFORM_IOS
    std::stringstream versionss;
    versionss << "#version " << deviceCaps.MajorVersion << deviceCaps.MinorVersion << "0 es\n";
    GLSLSource.append(versionss.str());
```
Because, version of android vulkan is set in the RenderDeviceVkImpl.cpp like this.
```
    m_DeviceCaps.DevType = DeviceType::Vulkan;
    m_DeviceCaps.MajorVersion = 1;
    m_DeviceCaps.MinorVersion = 0;
```

**Comment by DiligentGraphics** [comment]
Ah, overlooked Vulkan. This should fix it: https://github.com/DiligentGraphics/DiligentCore/commit/746ad343c7dbc565ff6008e58f7b85155694842e

**Comment by dom607** [comment]
You forgot to modify GLSLSourceBuilder.h and ShaderVkImpl.cpp and ShaderGLImpl.cpp. :D

**Comment by DiligentGraphics** [comment]
What do you mean? This didn't fix the problem?

**Comment by dom607** [comment]
Sorry, never mind. My mistake. I think, I missed something when merge branch.

**Comment by dom607** [comment]
After merge latest DiligentCore commit:https://github.com/DiligentGraphics/DiligentCore/commit/d2ffc2c44c32c94bff4091c650fb51f09f819b7f, this error occurred when test DiligentSamples.
```
2019-02-21 17:03:38.700 21784-21812/com.diligentengine.tutorial02_cube.Tutorial02Application E/Diligent Engine: Diligent Engine: ERROR: Failed to parse shader source: 
    ERROR: 0:43: 'gl_Position' : identifiers starting with "gl_" are reserved 
    ERROR: 0:43: 'location' : SPIR-V requires location for user input/output 
    ERROR: 2 compilation errors.  No code generated.
2019-02-21 17:03:38.700 21784-21812/com.diligentengine.tutorial02_cube.Tutorial02Application A/Diligent Engine: Diligent Engine: CRITICAL ERROR in ShaderVkImpl() (ShaderVkImpl.cpp, 68): Failed to compile shader
2019-02-21 17:03:38.701 21784-21812/com.diligentengine.tutorial02_cube.Tutorial02Application E/Diligent Engine: Diligent Engine: ERROR in CreateDeviceObject() (RenderDeviceBase.h, 462): Failed to create shader object "AntTwBar: LineRectVS"
2019-02-21 17:03:38.702 21784-21812/com.diligentengine.tutorial02_cube.Tutorial02Application A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 21812 (Thread-2), pid 21784 (al02Application)
2019-02-21 17:03:38.746 21818-21818/? A/DEBUG: pid: 21784, tid: 21812, name: Thread-2  >>> com.diligentengine.tutorial02_cube.Tutorial02Application <<<
2019-02-21 17:03:38.746 21818-21818/? A/DEBUG: Abort message: 'Diligent Engine: CRITICAL ERROR in ShaderVkImpl() (ShaderVkImpl.cpp, 68): Failed to compile shader
```
In my guess, this problem is relate to GLES 3.0 support issue. TwBarLib is already used in many places on DiligentSamples, I stopped testing with DiligentSamples. 
Anyway the cube sample(HLSL) in my sample project, it is work with latest commit. 

This is change for test vulkan-android

- DiligentEngine/Common/NativeApp/Android/src/build.grade
```
    defaultConfig {
        ndk {
            abiFilters 'arm64-v8a'//, 'armeabi', 'arm64-v8a','x86', 'x86_64'
        }
        externalNativeBuild {
            cmake {
                arguments '-DANDROID_PLATFORM=android-24',
                        '-DANDROID_TOOLCHAIN=clang', '-DANDROID_STL=c++_static', '-DENABLE_TESTS=TRUE'
            }
        }
    }
    externalNativeBuild {
        cmake {
            path '../../../CMakeLists.txt'
            version "3.10.2"
        }
    }
```

- DiligentEngine/DiligentSamples/Samples/SampleBase/src/android/SampleAppAndroid.cpp
```
    SampleAppAndroid()
    {
        m_DeviceType = DeviceType::Vulkan;
    }
```

**Comment by DiligentGraphics** [comment]
Yes, there was the same issue on desktop Vulkan, it should be fixed now.
I am sorry I still did not merge your change, I am swamped with other issues now.

**Comment by dom607** [comment]
I have merged latest commit.(GLES fix) I did a simple test with tutorial3 and tutorial4, and it was okay.

**Comment by DiligentGraphics** [comment]
Could you please create a new pull request with just the required changes? It seems like there have been some experimental changes that I don't think makes sense to keep in history (such as adding and removing binary libraries)?
Thanks again for helping with this issue.

**Comment by dom607** [comment]
Ok, I got it.

**Pull request closed without merging**
