### PR TITLE
WebGPU: Implemented texture uploader (close #556)

### LINKED ISSUE #556: WebGPU: implement texture uploader
Two options:
* Use WriteTexture
* Create immutable staging buffer each time

@MikhailGorobets Find out which way is preferable for performance

### PR DESCRIPTION
**Pull request by MikhailGorobets**

### CODE REVIEW

**Comment by TheMostDiligent** [comment]
`TextureUploaderWebGPU` is a verbatim copy of `TextureUploaderGL`.
If they are identical, we should combined them into `TextureUploaderGL_WGPU` similar to `TextureUploaderD3D12_Vk`

**Comment by TheMostDiligent** [comment]
@MikhailGorobets why would we need `MapAsync`. It is only for readback.

**Comment by MikhailGorobets** [comment]
https://gh.whitespider.dev/gpuweb/gpuweb/discussions/4733

**Review by TheMostDiligent — APPROVED** [review]

**Comment by TheMostDiligent** [comment]
@MikhailGorobets please merge this PR when checks complete

**Pull request merged**
